'use client';
import { ArrowUpRight, Command, MoreHorizontal, Plus, ChevronDown, Layers, MousePointer2, Check, CreditCard, Activity, Circle, BarChart3, Box, Zap } from 'lucide-react';

export function InstagramIcon({size=17}:{size?:number}){return <svg width={size} height={size} viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><rect x="2" y="2" width="20" height="20" rx="5"/><circle cx="12" cy="12" r="4.2"/><circle cx="17.5" cy="6.5" r="1.2" fill="currentColor" stroke="none"/></svg>}
export function YoutubeIcon({size=17}:{size?:number}){return <svg width={size} height={size} viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M22.54 6.42a2.78 2.78 0 0 0-1.94-2C18.88 4 12 4 12 4s-6.88 0-8.6.46a2.78 2.78 0 0 0-1.94 2A29 29 0 0 0 1 11.75a29 29 0 0 0 .46 5.33 2.78 2.78 0 0 0 1.94 1.96c1.72.46 8.6.46 8.6.46s6.88 0 8.6-.46a2.78 2.78 0 0 0 1.94-1.96 29 29 0 0 0 .46-5.33 29 29 0 0 0-.46-5.33z"/><path d="m9.75 15.02 5.75-3.27-5.75-3.27z" fill="currentColor"/></svg>}
export function XIcon({size=17}:{size?:number}){return <svg width={size} height={size} viewBox="0 0 24 24" fill="currentColor"><path d="M18.9 1.15h3.68l-8.04 9.19L24 22.85h-7.41l-5.8-7.58-6.64 7.58H.47l8.6-9.83L0 1.15h7.59l5.24 6.93zm-1.29 19.5h2.04L6.49 3.24H4.3z"/></svg>}
export function Brand({small=false}:{small?:boolean}){return <span className={'brand '+(small?'brand-small':'')}><span className="brand-icon"><Layers size={21} strokeWidth={2.7}/></span>Experiments<span className="brand-dot">_</span>Projects</span>}
export function MiniDashboard({hero=false}:{hero?:boolean}){return <div className={'mini-dashboard '+(hero?'mini-hero':'')}><div className="mini-sidebar"><strong><Command size={12}/> nexus</strong><span className="mini-nav-active"><Box/> Overview</span><span><BarChart3/> Analytics</span><span><Circle/> Customers</span><span><CreditCard/> Payments</span><span><Layers/> Products</span><div className="mini-sidebar-bottom">✦ &nbsp; Pro workspace</div></div><div className="mini-main"><div className="mini-top"><span>Workspace <b>/ Overview</b></span><span>⌘ K　◉</span></div><div className="mini-title"><b>Overview</b><span>This month <ChevronDown size={7}/></span></div><div className="mini-metrics"><div><span>Total revenue <ArrowUpRight/></span><b>₹48,29,500</b><small>↗ 18.6% <i>vs last month</i></small></div><div><span>Active users <Activity/></span><b>2,845</b><small>↗ 12.4% <i>vs last month</i></small></div><div><span>Conversion rate</span><b>4.82%</b><small>↗ 2.1%</small></div></div><div className="mini-chart"><div><b>Revenue overview</b><span>↗ +18.6%　•••</span></div><div className="chart-inner"><div className="chart-labels"><span>50k</span><span>30k</span><span>10k</span></div><svg viewBox="0 0 400 100" preserveAspectRatio="none"><defs><linearGradient id={hero?'herograd':'minigrad'} x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor="#c6f575" stopOpacity=".36"/><stop offset="100%" stopColor="#c6f575" stopOpacity="0"/></linearGradient></defs><path d="M0 88 Q15 87 27 77 T54 72 T81 81 T108 52 T135 60 T162 35 T189 46 T216 22 T243 36 T270 15 T297 25 T324 7 T351 14 T378 2 L400 0 L400 100 L0 100 Z" fill={`url(#${hero?'herograd':'minigrad'})`}/><path d="M0 88 Q15 87 27 77 T54 72 T81 81 T108 52 T135 60 T162 35 T189 46 T216 22 T243 36 T270 15 T297 25 T324 7 T351 14 T378 2 L400 0" fill="none" stroke="#b8ec62" strokeWidth="2.3"/></svg></div><div className="chart-months">Jan <span>Feb</span><span>Mar</span><span>Apr</span><span>May</span><span>Jun</span></div></div><div className="mini-transactions"><b>Recent transactions</b><span>View all ↗</span></div>{['Linear workspace','Figma professional','Vercel pro'].map((s,i)=><div className="mini-row" key={s}><i style={{background:['#bbb2f9','#edb090','#a7c9f7'][i]}}/><b>{s}</b><span>Monthly subscription</span><em>Completed</em><strong>₹{[2400,1490,2000][i]}</strong></div>)}</div></div>}
export function OrbitVisual(){return <div className="orbit-visual"><div className="orbit-copy"><span>CREATE WITHOUT LIMITS</span><b>Beyond the<br/>ordinary.</b><small>Extraordinary experiences.<br/>Endless possibilities.</small><i>Explore the future ↗</i></div><div className="orbit-art"><div className="orbit-ring ring-one"/><div className="orbit-ring ring-two"/><div className="orbit-ring ring-three"/><div className="orbit-core"/></div><span className="orbit-caption">A NEW DIMENSION OF DIGITAL</span></div>}
export function PricingVisual(){return <div className="pricing-visual"><small>SIMPLE PRICING. LIMITLESS POTENTIAL.</small><b>The right plan for your next big thing.</b><div className="tiny-plans">{[['Starter','499'],['Pro','1,499'],['Team','3,999']].map(([name,price],i)=><div className={i===1?'tiny-plan selected':'tiny-plan'} key={name}>{i===1&&<em>MOST POPULAR</em>}<span>{name}</span><strong>₹{price}<small>/mo</small></strong><p>Everything you need to get going.</p><button tabIndex={-1}>Get started ↗</button><hr/>{['Unlimited projects','All core features','Community access','Lifetime updates'].map(x=><small key={x}><Check size={7}/>{x}</small>)}</div>)}</div></div>}
export function LandingVisual(){return <div className="landing-visual"><div className="landing-nav"><b>vertex<span>✳</span></b><small>Product　 Solutions　 Resources</small><i>Get started ↗</i></div><span className="landing-pill">✦ LESS FRICTION. MORE MOMENTUM.</span><h3>Your next big idea.<br/><em>Built to take off.</em></h3><p>One workspace. Infinite possibilities.<br/>For teams ready to do something great.</p><div className="landing-buttons"><b>Start building ↗</b><span>See how it works →</span></div><div className="landing-tiles"><div><BarChart3/><span>Built for your flow</span></div><div><Zap/><span>Move at your speed</span></div><div><Layers/><span>Everything, connected</span></div></div></div>}
/** Renders visual artwork for hardware devices, source code, and modules. */
export function HardwareVisual({variant='module'}:{variant?:'board'|'module'|'antenna'|'kit'|'device'|'code'}){
  const pins=(n:number,cls='')=>(<span className={'hw-pins '+cls}>{Array.from({length:n}).map((_,i)=><i key={i}/>)}</span>);
  if(variant==='code')return <div className="hw-visual hw-code"><div className="code-editor-box"><div className="code-editor-top"><span/><span/><span/><i>firmware.cpp</i></div><div className="code-editor-lines"><p><span className="c-kw">#include</span> &lt;ESP32.h&gt;</p><p><span className="c-fn">void</span> <span className="c-hl">setup</span>() &#123;</p><p>&nbsp;&nbsp;Radio.<span className="c-fn">begin</span>(433E6);</p><p>&nbsp;&nbsp;WiFi.<span className="c-fn">connect</span>();</p><p>&#125;</p></div></div><small className="hw-caption">FULL SOURCE · READY TO FLASH</small></div>;
  if(variant==='device')return <div className="hw-visual hw-device"><div className="device-enclosure"><div className="device-screen"><span className="screen-dot"/><b>AI ACTIVE</b><small>240×320 TFT</small></div><div className="device-controls"><span/><span/><span/></div></div><small className="hw-caption">ASSEMBLED &amp; TESTED DEVICE</small></div>;
  if(variant==='antenna')return <div className="hw-visual hw-antenna"><div className="hw-whip"><b/><span/><span/><span/><span/></div><div className="hw-sma"><i/></div><small>5 dBi · 2.4 GHz</small></div>;
  if(variant==='kit')return <div className="hw-visual hw-kit"><div className="hw-piece hw-a"><i/><small>MCU</small></div><div className="hw-piece hw-b"><i/><small>RF</small></div><div className="hw-piece hw-c"><i/><small>ANT</small></div><span className="hw-brace">PAIR · READY TO DEPLOY</span></div>;
  if(variant==='board')return <div className="hw-visual hw-board"><span className="hw-usb"/><span className="hw-ant-trace"/><div className="hw-shield"><b>WROOM</b><i/></div><span className="hw-chip"/><span className="hw-led"/>{pins(12,'hw-top')}{pins(12,'hw-bot')}<small className="hw-caption">DUAL-CORE · 240 MHz</small></div>;
  return <div className="hw-visual hw-module"><span className="hw-coil"/><div className="hw-shield hw-shield-sm"><b>RF</b><i/></div><span className="hw-crystal"/>{pins(4,'hw-top')}{pins(4,'hw-bot')}<small className="hw-caption">SPI · 3.3 V</small></div>;
}

export function ProductVisual({kind,image,name}:{kind:string;image?:string|null;name?:string}){if(image)return <img src={image} alt={name||'Component preview'} className="product-image"/>;if(kind==='hardware-code'||kind==='source-code')return <div className="hardware-preview"><HardwareVisual variant="code"/></div>;if(kind==='hardware-device'||kind==='device')return <div className="hardware-preview"><HardwareVisual variant="device"/></div>;if(kind==='hardware-board')return <div className="hardware-preview"><HardwareVisual variant="board"/></div>;if(kind==='hardware-module')return <div className="hardware-preview"><HardwareVisual variant="module"/></div>;if(kind==='hardware-antenna')return <div className="hardware-preview"><HardwareVisual variant="antenna"/></div>;if(kind==='hardware-kit')return <div className="hardware-preview"><HardwareVisual variant="kit"/></div>;if(kind==='dashboard')return <div className="dashboard-preview"><MiniDashboard/></div>;if(kind==='orbit')return <OrbitVisual/>;if(kind==='pricing')return <PricingVisual/>;if(kind==='landing')return <LandingVisual/>;if(kind==='buttons')return <div className="buttons-visual"><small>SMALL DETAILS. BIG IMPACT.</small><h3>A little more <em>interaction.</em></h3><div><span>Get started <ArrowUpRight size={13}/></span><span>Explore more <Plus size={13}/></span><span>Make it happen <Zap size={13}/></span></div><MousePointer2 className="button-cursor"/><small>THE PULSE BUTTON COLLECTION</small></div>;if(kind==='login')return <div className="login-visual"><div><span>flow®</span><h3>A little focus.<br/>A lot of possibility.</h3><div className="login-orb"/><small>YOUR NEXT CHAPTER STARTS HERE.</small></div><div><b>Welcome back.</b><small>Good things are waiting for you.</small><span className="fake-input">Email address</span><span className="fake-input">Password</span><i>Sign in →</i><small>New here? Create an account</small></div></div>;if(kind==='portfolio')return <div className="portfolio-visual"><b>nova® <span>AVAILABLE FOR WORK ↗</span></b><h3>Making digital<br/><em>feel human.</em></h3><div><span>Form &<br/>Function <ArrowUpRight/></span><span>Tomorrow,<br/>today. <ArrowUpRight/></span></div></div>;return <div className="aurora-visual"><span>LIGHT. COLOR. POSSIBILITY.</span><h3>A different kind<br/>of atmosphere.</h3><i>Step into something new ↗</i><div/></div>}
export function HeroScene(){return <div className="hero-scene" onMouseMove={e=>{const r=e.currentTarget.getBoundingClientRect();e.currentTarget.style.setProperty('--mx',`${((e.clientX-r.left)/r.width-.5)*6}deg`);e.currentTarget.style.setProperty('--my',`${((e.clientY-r.top)/r.height-.5)*-6}deg`);}} onMouseLeave={e=>{e.currentTarget.style.setProperty('--mx','0deg');e.currentTarget.style.setProperty('--my','0deg');}}><div className="scene-glow"/><div className="scene-grid"/><div className="floating-tag tag-code"><span>⌘</span> Built for developers</div><div className="scene-dashboard"><div className="scene-window"><span/><span/><span/><i>nexus / overview</i><MoreHorizontal size={13}/></div><MiniDashboard hero/></div><div className="scene-payment"><div><span className="payment-icon"><CreditCard size={18}/></span><MoreHorizontal size={18}/></div><small>Total balance</small><b>₹24,680<span>.00</span></b><div className="payment-bottom"><span><i/> +12.8% this month</span><span>↗</span></div></div><div className="scene-purple"><div><span>Weekly activity</span><ArrowUpRight size={16}/></div><b>+32.6<span>%</span></b><div className="purple-bars">{[30,49,37,61,51,77,94].map((n,i)=><i style={{height:n+'%'}} key={i}/>)}</div><small>M　 T　 W　 T　 F　 S　 S</small></div><div className="floating-tag tag-production"><span><Check size={11}/></span> Production ready</div><div className="scene-orbit"><div/><div/></div><div className="scene-spark spark-one">✧</div><div className="scene-spark spark-two">✦</div><div className="scene-cursor"><MousePointer2 size={24} fill="#ccf775"/><span>your next big idea</span></div></div>}
