import 'dotenv/config';
import { chromium, expect } from '@playwright/test';
import { drizzle } from 'drizzle-orm/node-postgres';
import { sql } from 'drizzle-orm';
import pg from 'pg';
import { unlink } from 'node:fs/promises';
import { randomBytes } from 'node:crypto';

const base=process.env.TEST_BASE_URL||'http://localhost:3000';
const email='stackd-smoke@example.test';
const password=randomBytes(24).toString('hex');
const browser=await chromium.launch({headless:true,args:['--no-sandbox']});
const page=await browser.newPage({viewport:{width:1440,height:1000}});
const errors=[];let createdOwner=false;let uploadedFile='';
page.on('pageerror',e=>errors.push(e.message));
try{
 await page.goto(base,{waitUntil:'networkidle'});
 await expect(page.locator('.product-card')).toHaveCount(8);
 await page.getByRole('button',{name:'Add Nexus — Analytics Dashboard to cart',exact:true}).click();
 await page.getByRole('button',{name:'Shopping cart, 1 items',exact:true}).click();
 await page.getByRole('button',{name:'Continue to checkout'}).click();
 await page.getByLabel('Full name').fill('Smoke Test Builder');
 await page.getByLabel('Email address',{exact:true}).fill(email);
 await page.getByRole('checkbox').check();
 const orderResponse=page.waitForResponse(r=>r.url()===base+'/api/orders'&&r.request().method()==='POST');
 await page.getByRole('button',{name:'Place invoice order'}).click();
 const order=await (await orderResponse).json();
 await expect(page.getByText('Order received. Thank you!',{exact:true})).toBeVisible();
 if(order.status!=='pending'||order.total!==4900)throw Error('Invoice checkout mismatch');
 await page.getByRole('link',{name:'View order',exact:true}).click();
 await expect(page.getByRole('heading',{name:'You’re one step closer.'})).toBeVisible();
 console.log('PASS: cart, invoice checkout, private order page');

 const auth=await (await fetch(base+'/api/admin/session')).json();
 if(auth.needsSetup){
  await page.goto(base+'/admin');
  await page.getByLabel('Email address',{exact:true}).fill(email);
  await page.getByLabel('Create a password').fill(password);
  await page.getByRole('button',{name:'Create owner account'}).click();
  await expect(page.getByRole('heading',{name:'A little perspective. A lot of potential.'})).toBeVisible();
  createdOwner=true;
  await page.getByRole('button',{name:'Add component',exact:true}).click();
  await page.getByLabel('Component name *',{exact:true}).fill('Smoke Test — Component');
  await page.getByLabel('Description *',{exact:true}).fill('A temporary component created by the end-to-end validation suite.');
  await page.getByLabel(/^Price \(USD\)/).fill('12.50');
  await page.getByLabel('Downloadable HTML source').fill('<!DOCTYPE html><html><body><h1>Smoke-test downloadable source</h1></body></html>');
  const uploadResponse=page.waitForResponse(r=>r.url()===base+'/api/upload');
  await page.locator('.upload-label input').setInputFiles({name:'smoke.png',mimeType:'image/png',buffer:Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+jB5kAAAAASUVORK5CYII=','base64')});
  const upload=await (await uploadResponse).json();
  if(!upload.url)throw Error('Image upload failed');
  uploadedFile=upload.url.split('/').pop();
  await expect(page.getByRole('button',{name:'Publish component',exact:true})).toBeEnabled();
  await page.getByRole('button',{name:'Publish component',exact:true}).click();
  await expect(page.getByRole('dialog')).toHaveCount(0);
  await page.locator('.admin-sidebar nav').getByRole('button',{name:'Components',exact:true}).click();
  await expect(page.getByText('Smoke Test — Component',{exact:true})).toBeVisible();
  console.log('PASS: admin setup, image upload, source upload, product publication');
  await page.locator('.admin-sidebar nav').getByRole('button',{name:/^Orders/}).click();
  const row=page.getByRole('row').filter({hasText:order.id});
  await row.getByRole('button',{name:'Mark paid'}).click();
  await page.getByRole('button',{name:'Yes, payment received'}).click();
  await expect(page.getByRole('dialog')).toHaveCount(0);
  await expect(row.locator('.status')).toHaveText('paid');
  const download=await fetch(base+`/api/download/nexus-dashboard?token=${order.token}`);
  if(download.status!==200||!download.headers.get('content-disposition')?.includes('attachment'))throw Error('Purchased download failed');
  const noToken=await fetch(base+'/api/download/nexus-dashboard');
  if(noToken.status!==403)throw Error('Paid download is not protected');
  await page.screenshot({path:'artifacts/admin-orders.png'});
  console.log('PASS: payment confirmation and protected downloads');
 }
 await page.goto(base,{waitUntil:'networkidle'});
 await page.getByRole('button',{name:'Search components',exact:true}).click();
 await page.getByLabel('Search catalog').fill('Orbit');
 await page.locator('.search-results').getByRole('button',{name:/Orbit/}).click();
 await expect(page.getByRole('dialog')).toBeVisible();
 await page.getByRole('button',{name:'Live preview',exact:true}).click();
 await expect(page.locator('.component-iframe')).toBeVisible();
 await page.getByLabel('Close dialog').click();
 await page.getByRole('button',{name:'Save Orbit — 3D Hero Section',exact:true}).click();
 await page.getByRole('button',{name:'Filter saved components',exact:true}).click();
 await expect(page.locator('.product-card')).toHaveCount(1);
 await page.getByRole('button',{name:'Filter saved components',exact:true}).click();
 await page.getByLabel('Email address for newsletter').fill(email);
 await page.getByRole('button',{name:'Count me in',exact:true}).click();
 await expect(page.locator('.subscribed-state')).toBeVisible();
 console.log('PASS: search, live preview, saved filtering, newsletter subscription');
 await page.setViewportSize({width:390,height:844});
 await page.goto(base,{waitUntil:'networkidle'});
 if(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth))throw Error('Mobile horizontal overflow');
 await page.getByRole('button',{name:'Toggle menu'}).click();
 await page.locator('.main-nav').getByRole('button',{name:'Freebies',exact:true}).click();
 await expect(page.locator('.product-card')).toHaveCount(1);
 await page.getByRole('button',{name:'Pulse — Interactive Buttons',exact:true}).click();
 const freeDownload=page.waitForEvent('download');
 await page.getByRole('link',{name:'Download',exact:true}).click();
 if(!(await freeDownload).suggestedFilename().endsWith('.html'))throw Error('Free download missing');
 console.log('PASS: mobile navigation, category filtering, real free download');
 if(errors.length)throw Error('Browser errors: '+errors.join('\n'));
 console.log('ALL SMOKE TESTS PASSED');
}finally{
 await browser.close();
 const pool=new pg.Pool({connectionString:process.env.DATABASE_URL});
 const db=drizzle(pool);
 await db.execute(sql`delete from orders where email in (${email}, 'test-checkout@example.test')`);
 await db.execute(sql`delete from products where name = 'Smoke Test — Component'`);
 await db.execute(sql`delete from subscribers where email = ${email}`);
 if(createdOwner){await db.execute(sql`delete from sessions where admin_id in (select id from admins where email = ${email})`);await db.execute(sql`delete from admins where email = ${email}`);}
 if(uploadedFile)await unlink('uploads/'+uploadedFile).catch(()=>{});
 await pool.end();
 console.log('Temporary test data removed; owner setup remains available.');
}
